#!/usr/bin/env python

# ensure it is in ReST so PyPI is happy
"""
Python-HostConf
===============

This is a package which is a replacement for GNU autoconf support for a package which needs to "inspect" the local host system to see if it needs some special local configurations to make it work.

  The idea is to replace the 'configure' script generated by an assortment of autoconf tools (... along with all of the dependencies of sed, gawk, (g)make, ... with a pure Python implementation.

  It has been developed during the porting of python-editline.  It requires libedit (ala NetBSD), and the main, multiplatform distro of it uses autoconf.  This i pretty handy, but it carries a lot of baggage.

  Python-Editline now relies only on Python and the compiler available to do all of the host detection (libraries, header files, types, ...)


Have a look at the README.md in the source repo.

"""

import sys
import os
from distutils.core import setup

import hostconf

setup(
    name='python-hostconf',
    version=hostconf.version(),
    description='A host inspection/configuration tool to replace autoconf',
    long_description=__doc__,
    packages=[
        'hostconf',
        'hostconf.tests'
    ],
    url='https://github.com/mark-nicholson/python-hostconf',
    author='Mark Nicholson',
    author_email='nicholson.mark@gmail.com',
    license='BSD',
    python_requires='>=3.3',
    classifiers=[
        'Environment :: Console',
        'Intended Audience :: End Users/Desktop',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
    ]
)
